### ISSUE TITLE
000-org-build: have OrganizationFormationInitialCommit download initial-commit over http

### ISSUE THREAD

**Issue by OlafConijn** [org-formation/org-formation-reference#8]
would be great to have the OrganizationFormationInitialCommit task download the initial commit from a central repo. this will require an issue to be made over at org-formation-cli to allow for https:// or s3:// sources?

consider to change attributes to SourcePath/TargetPath? 

``` yml
OrganizationFormationInitialCommit:
  Type: copy-to-s3
  DependsOn: OrganizationFormationBuckets
  LocalPath: 'initial-commit.zip'
  RemotePath: !Sub 's3://organization-formation-deployments-${accountId}-prd/initial-commit.zip'
  OrganizationBinding:
    Account: !Ref accountId
    Region: !Ref primaryRegion
```
